APT {
FTPArchive {
Release {
Origin "jb.illixion.com";
Label "jb.illixion.com";
Suite stable;
Version 1.0;
Codename CODENAME_HERE;
Architectures iphoneos-arm;
Components main;
Description "Manual's Repo";
};
};
};
